[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "test_archive"
version = "0.1.0"

[tool.setuptools.packages.find]
where = ["."]
include = ["test_archive*"]


