[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "housing_project"
version = "1.0.0"
description = "Housing project"

[tool.setuptools.packages.find]
where = ["."]
include  = ["src*"]